import json,re,time,pathlib,sys,tempfile,shutil,subprocess,hashlib,secrets,os
from urllib.parse import urlsplit,parse_qs
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(sys.argv[1] if len(sys.argv)>1 else 'nabd').resolve()
SRC=ROOT/'v2-src'
TEST_PASSWORD='nabd-fixture-login-only-not-live'
TEST_SITE=pathlib.Path(tempfile.mkdtemp(prefix='nabd-test-'))
for name in ['index.html','wall.html']:shutil.copy(ROOT/name,TEST_SITE/name)
auth=json.loads((SRC/'auth.json').read_text());auth['salt']=secrets.token_hex(24);auth['hash']=hashlib.pbkdf2_hmac('sha256',TEST_PASSWORD.encode(),bytes.fromhex(auth['salt']),auth['iterations'],32).hex()
wall=(TEST_SITE/'wall.html').read_text();wall=re.sub(r'const V2AUTH=\{[^;]+;',lambda m:'const V2AUTH='+json.dumps(auth)+';',wall,count=1);(TEST_SITE/'wall.html').write_text(wall)
server=subprocess.Popen([sys.executable,'-m','http.server','8123','--directory',str(TEST_SITE)],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
time.sleep(.5)
members=json.loads((SRC/'members.json').read_text())
checks=[];errors=[]
def check(name,ok):
 checks.append({'test':name,'pass':bool(ok)});print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 if not ok:raise AssertionError(name)
def mock_api(route):
 u=route.request.url;path=urlsplit(u).path
 if '/profile/' in path:
  handle=path.split('/profile/')[1].split('/')[0];index=next((i for i,m in enumerate(members) if m['x']==handle),10)
  posts=[{'id':str(1900000000000000000+index*10000+j),'author':{'screen_name':handle,'name':members[index]['name'] if index<10 else handle},'text':'بيانات اختبار محلية فقط، غير منشورة. التحقق من ترتيب الحسابات وحجم البطاقات. '+str(j),'created_timestamp':int(time.time())-j*120-index,'likes':j,'retweets':0,'replies':0} for j in range(15)]
  route.fulfill(status=200,content_type='application/json',body=json.dumps({'code':200,'results':posts}))
 elif '/status/' in path:
  id=path.split('/')[-1];route.fulfill(status=200,content_type='application/json',body=json.dumps({'code':200,'status':{'id':id,'author':{'screen_name':'SalmaRashwani','name':'سلمى رشواني'},'text':'رابط اختبار محلي','created_timestamp':int(time.time())}}))
 else:route.fulfill(status=404,body='{}')
with sync_playwright() as pw:
 browser=pw.chromium.launch(headless=True,args=['--no-sandbox'])
 ctx=browser.new_context(viewport={'width':1440,'height':1000},locale='ar')
 ctx.route('https://api.fxtwitter.com/**',mock_api)
 ctx.route('https://www.facebook.com/**',lambda r:r.fulfill(status=200,content_type='text/html',body='<p>Local test of external frame boundary</p>'))
 ctx.route('https://platform.twitter.com/**',lambda r:r.abort())
 ctx.route('https://fonts.googleapis.com/**',lambda r:r.abort())
 ctx.route('https://fonts.gstatic.com/**',lambda r:r.abort())
 page=ctx.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.set_default_timeout(10000)
 try:
  page.goto('http://127.0.0.1:8123/',wait_until='domcontentloaded')
  frame=page.frame_locator('#content');frame.locator('#v2-auth').wait_for(timeout=30000);f=page.frames[1]
  f.wait_for_function('typeof window.NabdV2!=="undefined" && typeof busy!=="undefined" && !busy')
  check('Startup without JS errors',not errors)
  check('Ten X and ten Facebook sources',f.evaluate('state.accounts.length===10&&state.extra.facebook.length===10'))
  check('Ten displayed X posts',frame.locator('.tweet').count()==10)
  check('Balanced account representation',f.evaluate('new Set(selectedPosts().map(p=>p.handle)).size===10'))
  check('Default edit lock engaged',f.evaluate('NabdV2.status().locked'))
  page.screenshot(path=str(ROOT/'local-desktop.png'),animations='disabled')
  frame.locator('.hero-actions [data-action="accounts"]').click()
  check('Accounts require password',frame.locator('#v2-login').count()==1)
  frame.locator('#admin-password').fill('wrong-password')
  frame.locator('#login-submit').click()
  frame.locator('#login-error').filter(has_text='غير صحيحة').wait_for()
  check('Wrong password rejected',f.evaluate('NabdV2.status().locked'))
  frame.locator('#admin-password').fill(TEST_PASSWORD)
  frame.locator('#login-submit').click()
  frame.locator('#accounts-list').wait_for()
  check('Correct password unlocks settings',not f.evaluate('NabdV2.status().locked'))
  check('Facebook management contains ten profiles',frame.locator('[data-fb-limit]').count()==10)
  frame.locator('[data-action="close"]').first.click()
  frame.locator('#global-limit').fill('6');frame.locator('#global-limit').dispatch_event('change')
  check('Display count editable',frame.locator('.tweet').count()==6)
  frame.locator('.tweet [data-action="post-larger"]').first.click()
  check('Individual X card enlarges',frame.locator('.tweet .sizeval').first.inner_text()=='110%')
  frame.locator('[data-action="timer"]').first.click();frame.locator('#interval-setting').fill('12');frame.locator('[data-action="save-timer"]').click()
  check('Timer interval is editable and sent to shell',page.evaluate('NabdShell.stats().interval===12'))
  frame.locator('[data-action="pause"]').click()
  check('Automatic refresh can pause',not page.evaluate('NabdShell.stats().auto'))
  frame.locator('[data-action="platform"][data-platform="facebook"]').click()
  check('Facebook view has source cards, not fabricated posts',frame.locator('.fb-source').count()==10 and frame.locator('.fb-card').count()==0)
  frame.locator('[data-action="fb-preview"]').first.click()
  check('Public page embedding is offered honestly',frame.locator('.fb-preview iframe').count()==1)
  frame.locator('.v2-fb-heading [data-action="fb-add"]').click()
  frame.locator('#fb-links').fill('https://www.facebook.com/TestPage/posts/123456789012345?tracking=ignored\nhttps://www.facebook.com/TestPage/posts/123456789012345')
  frame.locator('#v2-fb-posts button[type="submit"]').click()
  check('Facebook post URLs deduplicate and strip tracking',f.evaluate('state.extra.fbPosts.length===1&&!state.extra.fbPosts[0].url.includes("tracking")'))
  frame.locator('[data-action="fb-larger"]').click()
  check('Facebook embedded card supports zoom',f.evaluate('state.extra.fbPosts[0].scale===1.1'))
  f.evaluate("document.cookie='nabd.temp=1; Path=/';document.cookie='unrelated_site_cookie=keep; Path=/other/'")
  f.evaluate("caches.open('nabd.cache.test').then(c=>c.put('/dummy',new Response('test')))")
  frame.locator('[data-action="platform"][data-platform="all"]').click()
  page.locator('#start-screen').click()
  page.wait_for_function('!!document.fullscreenElement',timeout=10000)
  check('Fullscreen activated from user click',page.evaluate('!!document.fullscreenElement'))
  before=page.evaluate('performance.timeOrigin');old=f.evaluate('performance.timeOrigin')
  page.locator('#hard-refresh').click()
  page.wait_for_function('NabdShell.stats().reloads>=1')
  page.wait_for_timeout(1500);f=page.frames[1];f.wait_for_function('typeof NabdV2!=="undefined" && !busy')
  check('Full inner document reloads while outer document persists',f.evaluate('performance.timeOrigin')!=old and page.evaluate('performance.timeOrigin')==before)
  check('Fullscreen survives full inner reload',page.evaluate('!!document.fullscreenElement'))
  check('Nabd cookies are deleted',not page.evaluate("document.cookie.includes('nabd.temp')"))
  check('Namespaced application cache cleared',page.evaluate("caches.keys().then(k=>!k.includes('nabd.cache.test'))"))
  check('Display and Facebook settings survive forced reload',f.evaluate('state.settings.limit===6&&state.settings.interval===12&&state.extra.fbPosts.length===1'))
  check('Edit lease survives forced inner reload',not f.evaluate('NabdV2.status().locked'))
  page.locator('#edit-settings').click();frame.locator('[data-action="close"]').first.click()
  frame.locator('#v2-auth').click()
  check('Manual lock works',f.evaluate('NabdV2.status().locked'))
  frame.locator('#global-limit').dispatch_event('change')
  check('Settings input blocked while locked',frame.locator('#v2-login').count()==1 and f.evaluate('state.settings.limit===6'))
  frame.locator('[data-action="close"]').first.click()
  f.evaluate('share()');share_url=frame.locator('#share-url').input_value()
  check('Share excludes passwords and auth records',TEST_PASSWORD not in share_url and 'admin.lease' not in share_url)
  other=ctx.new_page();other.on('pageerror',lambda e:errors.append(str(e)));other.goto(share_url,wait_until='domcontentloaded');other.locator('#gate-skip').click();other.wait_for_timeout(700)
  other.frames[1].wait_for_function('typeof NabdV2!=="undefined"&&!busy')
  check('Shared link preserves platform sources and remains read-only',other.frames[1].evaluate('sharedMode&&NabdV2.status().locked&&state.extra.facebook.length===10'))
  check('Noindex present in shell and inner document',page.locator('meta[name="robots"]').get_attribute('content').startswith('noindex') and frame.locator('meta[name="robots"]').get_attribute('content').startswith('noindex'))
  other.close();page.bring_to_front();page.evaluate('NabdShell.stop()');
  if frame.locator('#overlay').is_visible():frame.locator('[data-action="close"]').first.click()
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(400)
  check('Mobile shell and wall have no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth') and f.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  page.screenshot(path=str(ROOT/'local-mobile.png'),animations='disabled')
  check('No uncaught exceptions across interactions',not errors)
 except Exception as e:
  print('FAILURE',type(e).__name__,str(e),flush=True);page.screenshot(path=str(ROOT/'local-failure.png'));raise
 finally:
  (ROOT/'local-tests.json').write_text(json.dumps({'tests':checks,'errors':errors,'network':'local fixtures with a separate test-only password; no deployed password used or stored'},ensure_ascii=False,indent=2));browser.close();server.terminate();shutil.rmtree(TEST_SITE,ignore_errors=True)
